//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISNetwork
    {
        public int NetworkID { get; set; }
        public string username { get; set; }
        public string NetworkName { get; set; }
        public string NetworkTitle { get; set; }
        public string ServiceWSDL { get; set; }
        public string ServiceAbs { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string Organization { get; set; }
        public string website { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> SupportsAllMethods { get; set; }
        public string Citation { get; set; }
        public string MapIconPath { get; set; }
        public string OrgIconPath { get; set; }
        public Nullable<System.DateTime> LastHarvested { get; set; }
        public Nullable<bool> FrequentUpdates { get; set; }
        public byte[] logo { get; set; }
        public byte[] icon { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string NetworkVocab { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<float> Xmin { get; set; }
        public Nullable<float> Xmax { get; set; }
        public Nullable<float> Ymin { get; set; }
        public Nullable<float> Ymax { get; set; }
        public Nullable<long> ValueCount { get; set; }
        public Nullable<long> VariableCount { get; set; }
        public Nullable<long> SiteCount { get; set; }
        public Nullable<System.DateTime> EarliestRec { get; set; }
        public Nullable<System.DateTime> LatestRec { get; set; }
        public string ServiceStatus { get; set; }
        public Nullable<int> ServiceGroup { get; set; }
    }
}
