//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestArchive
    {
        public int Id { get; set; }
        public System.Guid ConfirmationNo { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string WSDL { get; set; }
        public int Seed { get; set; }
        public string GetValuesResult { get; set; }
        public string Username { get; set; }
    }
}
